version: '3.8'
services:
  g4lwebsockets_1:
    image: thecollabagepatch/g4lwebsockets:latest
    environment:
      - ENV_VARIABLE=value
    depends_on:
      - redis
      - mongo
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always

  g4lwebsockets_2:
    image: thecollabagepatch/g4lwebsockets:latest
    environment:
      - ENV_VARIABLE=value
    depends_on:
      - redis
      - mongo
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["2"]
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always

  concurrent_gary_1:
    image: thecollabagepatch/concurrent_gary:latest
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
      - PYTORCH_NO_CUDA_MEMORY_CACHING=1
    depends_on:
      - redis
      - mongo
    entrypoint: ["/usr/src/app/concurrent_gary-entrypoint.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["3"]
              capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/generate || curl -f http://localhost:8001/continue || curl -f http://localhost:8001/tasks"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always

  concurrent_gary_2:
    image: thecollabagepatch/concurrent_gary:latest
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
      - PYTORCH_NO_CUDA_MEMORY_CACHING=1
    depends_on:
      - redis
      - mongo
    entrypoint: ["/usr/src/app/concurrent_gary-entrypoint.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["4"]
              capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/generate || curl -f http://localhost:8001/continue || curl -f http://localhost:8002/tasks"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always

  express-server:
    image: thecollabagepatch/express-server:latest
    ports:
      - "26532:3000"
    environment:
      - ENV_VARIABLE=value
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/combine-audio"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always

  redis:
    image: thecollabagepatch/redis:latest
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    ports:
      - "26530:80"
      - "26531:26531"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - concurrent_gary_1
      - concurrent_gary_2
      - g4lwebsockets_1
      - g4lwebsockets_2

  cron:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cron:/etc/crontabs/root
    entrypoint: /bin/sh -c "crond -f"

volumes:
  mongo-data: