version: '3.8'
services:
  g4lwebsockets:
    image: thecollabagepatch/g4lwebsockets:latest  # Use the local image
    build:
      context: .
      dockerfile: Dockerfile.g4lwebsockets
    ports:
      - "8000:8000"
    environment:
      - ENV_VARIABLE=value  # Add any required environment variables here
    depends_on:
      - redis
      - mongo
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
