name: audiocraft_build
description: 'Build audiocraft env.'
runs:
  using: "composite"
  steps:
  - uses: actions/setup-python@v2
    with:
<<<<<<< HEAD
      python-version: 3.8
=======
      python-version: 3.9
>>>>>>> audiocraft/main
  - uses: actions/cache@v2
    id: cache
    with:
      path: env
      key: audiocraft_env-${{ hashFiles('**/requirements.txt') }}

  - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
    name: Install dependencies
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install libsndfile1-dev ffmpeg
      python3 -m venv env
      .  env/bin/activate
      python -m pip install --upgrade pip
<<<<<<< HEAD
      pip install torch torchvision torchaudio
      pip install xformers
      pip install -e '.[dev]'
=======
      pip install 'numpy<2' torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0
      pip install xformers
      pip install -e '.[dev,wm]'
>>>>>>> audiocraft/main
  - name: System Dependencies
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install libsndfile1-dev ffmpeg
