global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'g4lwebsockets'
    static_configs:
      - targets: ['g4lwebsockets:8000']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'mongodb_exporter'
    static_configs:
      - targets: ['mongodb_exporter:9216']
