name: audiocraft_docs
on:
  push:
    branches: [ main ]

jobs:
  run_docs:
    name: Run docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/audiocraft_build
      - name: Config git
        run: |
          git config --global user.email "defossez@fb.com"
          git config --global user.name "Alexandre Défossez (autodoc)"

      - name: Reset branch
        run: |
          git branch -f gh-docs main
          git checkout gh-docs

      - name: Make docs
        run: |
          . env/bin/activate
          make api_docs
          git add -f api_docs
          git commit -m api_docs

      - name: Push branch
        run: |
          git push -f -u origin gh-docs
